# -*- coding: utf-8 -*-
"""Project_FCNN_CNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MiWECYTU-2bHWYxLc3vg-l4kNBDme8KK
"""

import torch
import torch.nn as nn
import torch.optim as optim
import matplotlib.pyplot as plt
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms # Can skip
import pandas as pd
import numpy as np

# HYPERPARAMETER
BATCH_SIZE = 64
EPOCHS = 15
LEARNING_RATE = 0.005

'''
To Transform any numpy array into tensor for pytorch
Compose() -> chains multiple
Images in the format of (H, W, C) which is then converted into (C, H, W) following which the pixel values are scaled between 0 and 1.
Normalization using Gaussian and std. deviation.
'''
trans = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.1307,), (0.3801,))
])

class MNISTDataset(Dataset):
  def __init__(self, csv_file, transform=None, shift_place=0):
    self.df = pd.read_csv(csv_file)
    self.transform = transform
    self.shift_place = shift_place

  def __len__(self):
    return len(self.df)

  def __getitem__(self, idx):
        label = self.df.iloc[idx]['label']
        image = self.df.iloc[idx].drop('label').values.astype('float32')
        image = torch.tensor(image, dtype=torch.float32).view(28, 28) / 255.0 # To convert from NumPy to Tensor and apply Min-Max Scaling

        if self.shift_place > 0:
            image = self.shift_pixel(image, self.shift_place)

        image = image.unsqueeze(0) # To add the channel dimension.
        if self.transform:
            image = self.transform(image)
        return image, label  # This return the img shape as (784,).

  def shift_pixel(self, img_tensor, shift):
      shifted = torch.zeros_like(img_tensor)
      if shift < img_tensor.shape[1]:
          shifted[:, shift:] = img_tensor[:, :-shift]
      return shifted

# Define a transform for MNISTDataset that only normalizes, as ToTensor is handled internally
normalize_transform = transforms.Compose([
    transforms.Normalize((0.1307,), (0.3801,))
])

# MNISTDataset was defined because of local file, instead of using the std. library.
train_dataset = MNISTDataset('mnist_train.csv', transform=normalize_transform)
test_dataset = MNISTDataset('mnist_test.csv', transform=normalize_transform)

test_dataset_shift = MNISTDataset('mnist_test.csv', transform=normalize_transform, shift_place=5)

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=BATCH_SIZE, shuffle=False)
test_loader_shift = DataLoader(test_dataset_shift, batch_size=BATCH_SIZE, shuffle=False)

def visual(dataset, shifted, num_img=6):
  plt.figure(figsize=(12,5))
  for i in range(num_img):
    img, label = dataset[i]

    img_np = img.squeeze().numpy()

    img_shift, _ = shifted[i]
    img_shift_np = img_shift.squeeze().numpy()

    plt.subplot(2, num_img, i+1)
    plt.imshow(img_np, cmap='gray')
    plt.title(f'Label: {label}')
    plt.axis('off')

    plt.subplot(2, num_img, i+1+num_img)
    plt.imshow(img_shift_np, cmap='gray')
    plt.title(f'Label: {label}')
    plt.axis('off')

  plt.suptitle('Original Dataset vs Shifted Dataset Pre-Training Check', fontsize=14)
  plt.tight_layout()
  plt.show()

print('--- Training Dataset ---')
train_dataset = MNISTDataset('mnist_train.csv', transform=normalize_transform)
visual(train_dataset, test_dataset_shift)

class FNN(nn.Module):
  def __init__(self,):
    super(FNN, self).__init__()
    self.flatten = nn.Flatten()
    self.network = nn.Sequential(
        nn.Linear(784, 512),
        nn.ReLU(),
        nn.Linear(512, 128),
        nn.ReLU(),
        nn.Linear(128, 64),
        nn.ReLU(),
        nn.Linear(64, 10)
    )
  def forward(self, x):
    x = self.flatten(x)
    x = self.network(x)
    return x

class CNN(nn.Module):
  def __init__(self):
    super(CNN, self).__init__()
    self.conv1 = nn.Conv2d(1, 16, 3, 2, 2)
    self.bn1 = nn.BatchNorm2d(16)
    self.conv2 = nn.Conv2d(16, 32, 3, 2, 2)
    self.bn2 = nn.BatchNorm2d(32)
    self.conv3 = nn.Conv2d(32, 64, 3, 2, 2)
    self.bn3 = nn.BatchNorm2d(64)

    self.relu = nn.ReLU()
    self.dropout = nn.Dropout(0.3)

    self.fc = nn.Linear(64*6*6, 10)

  def forward(self, x):
    x = self.relu(self.bn1(self.conv1(x)))
    x = self.relu(self.bn2(self.conv2(x)))
    x = self.relu(self.bn3(self.conv3(x)))

    x = torch.flatten(x, 1)
    x = self.dropout(x)
    x = self.fc(x)

    return x

def count_trainable_parameters(model):
    return sum(p.numel() for p in model.parameters() if p.requires_grad)

fnn_model = FNN()
cnn_model = CNN()

print("ARCHITECTURAL COMPLEXITY SUMMARY")
print(f"FNN Total Trainable Parameters: {count_trainable_parameters(fnn_model):,}")
print(f"CNN Total Trainable Parameters:  {count_trainable_parameters(cnn_model):,}")

def train_model(model, train_loader, epochs, lr):
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    model = model.to(device)
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=lr)

    print(f"\n Training {model.__class__.__name__} on {device}")

    for epoch in range(epochs):
        model.train()
        running_loss = 0.0
        correct = 0
        total = 0

        for images, labels in train_loader:
            images, labels = images.to(device), labels.to(device)

            optimizer.zero_grad()
            outputs = model(images)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()

            running_loss += loss.item() * images.size(0)
            _, predicted = torch.max(outputs.data, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()

        epoch_loss = running_loss / len(train_loader.dataset)
        epoch_acc = (correct / total) * 100
        print(f"Epoch [{epoch+1}/{epochs}] | Loss: {epoch_loss:.4f} | Training Accuracy: {epoch_acc:.2f}%")

    return model

fnn_model = train_model(fnn_model, train_loader, epochs=EPOCHS, lr=LEARNING_RATE)

cnn_model = train_model(cnn_model, train_loader, epochs=EPOCHS, lr=LEARNING_RATE)

def metric_calculation(model, dataloader):
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    model.eval()

    all_predictions = []
    all_targets = []
    all_confidences = []

    with torch.no_grad():
        for images, labels in dataloader:
            images, labels = images.to(device), labels.to(device)
            outputs = model(images)

            # Apply Softmax to get probability distribution
            probs = torch.softmax(outputs, dim=1)
            # Find probability value of selected class and its label
            confidences, predicted = torch.max(probs, dim=1)

            all_predictions.extend(predicted.cpu().numpy())
            all_targets.extend(labels.cpu().numpy())
            all_confidences.extend(confidences.cpu().numpy())

    # Confusion matrix
    num_classes = 10
    confusion_matrix = np.zeros((num_classes, num_classes), dtype=int)
    for true_lbl, pred_lbl in zip(all_targets, all_predictions):
        confusion_matrix[true_lbl, pred_lbl] += 1

    accuracy = (np.array(all_predictions) == np.array(all_targets)).mean() * 100
    avg_confidence = np.mean(all_confidences) * 100

    return accuracy, avg_confidence, confusion_matrix

fnn_normal_acc, fnn_normal_conf, fnn_normal_cm = metric_calculation(fnn_model, test_loader)
fnn_shift_acc, fnn_shift_conf, fnn_shift_cm = metric_calculation(fnn_model, test_loader_shift)


cnn_normal_acc, cnn_normal_conf, cnn_norm_cm = metric_calculation(cnn_model, test_loader)
cnn_shift_acc, cnn_shift_conf, cnn_shift_cm = metric_calculation(cnn_model, test_loader_shift)

print(f"{'Model':<10} | {'Test Set':<20} | {'Accuracy (%)':<15} | {'Avg Confidence (%)':<20}")
print("-" * 75)
print(f"{'FNN':<10} | {'Standard':<20} | {fnn_normal_acc:<15.2f} | {fnn_normal_conf:<20.2f}")
print(f"{'FNN':<10} | {'Shifted (+5 Right)':<20} | {fnn_shift_acc:<15.2f} | {fnn_shift_conf:<20.2f}")
print("-" * 75)
print(f"{'CNN':<10} | {'Standard':<20} | {cnn_normal_acc:<15.2f} | {cnn_normal_conf:<20.2f}")
print(f"{'CNN':<10} | {'Shifted (+5 Right)':<20} | {cnn_shift_acc:<15.2f} | {cnn_shift_conf:<20.2f}")
print("="*75)

def plot_confusion(fnn_normal_cm, fnn_shift_cm, cnn_normal_cm, cnn_shift_cm):
    fig, axes = plt.subplots(2, 2, figsize=(14, 12))
    matrices = [
        (fnn_normal_cm, "FNN - Standard Test Set"),
        (fnn_shift_cm, "FNN - Shifted Test Set (+5 Right)"),
        (cnn_norm_cm, "CNN - Standard Test Set"),
        (cnn_shift_cm, "CNN - Shifted Test Set (+5 Right)")
    ]

    for idx, (matrix, title) in enumerate(matrices):
        ax = axes[idx // 2, idx % 2]
        im = ax.imshow(matrix, cmap='Blues', interpolation='nearest')

        fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04)

        ax.set_title(title, fontsize=12, fontweight='bold', pad=10)
        ax.set_xticks(np.arange(10))
        ax.set_yticks(np.arange(10))
        ax.set_xticklabels(np.arange(10))
        ax.set_yticklabels(np.arange(10))
        ax.set_xlabel("Predicted Label")
        ax.set_ylabel("True Label")

        threshold = matrix.max() / 2.0
        for i in range(10):
            for j in range(10):
                color = "white" if matrix[i, j] > threshold else "black"
                ax.text(j, i, format(matrix[i, j], 'd'),
                        ha="center", va="center", color=color, fontsize=9)

    plt.suptitle("Confusion Matrix Analysis: Architectural Robustness Comparison", fontsize=16, fontweight='bold', y=0.98)
    plt.tight_layout()
    plt.show()

plot_confusion(fnn_normal_cm, fnn_shift_cm, cnn_norm_cm, cnn_shift_cm)

def visual_differnce(fnn, cnn, dataset_normal, dataset_shifted, num_img=3):
  device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
  fnn.eval()
  cnn.eval()

  fig, axes = plt.subplots(num_img, 2, figsize=(10, num_img * 3.5))

  for i in range(num_img):
    img_nor, label = dataset_normal[i]
    img_shift, _ = dataset_shifted[i]

    normal_tensor = img_nor.unsqueeze(0).to(device)
    shift_tensor = img_shift.unsqueeze(0).to(device)

    with torch.no_grad():
      fnn_normal_pred = torch.argmax(fnn(normal_tensor)).item()
      fnn_shift_pred = torch.argmax(fnn(shift_tensor)).item()

      cnn_normal_pred = torch.argmax(cnn(normal_tensor)).item()
      cnn_shift_pred = torch.argmax(cnn(shift_tensor)).item()

    ax_normal = axes[i, 0]
    ax_normal.imshow(img_nor.squeeze().numpy(), cmap='gray')
    ax_normal.set_title(
        f'Original (True Label: {label}) \n'
        f'FNN Prediction: {fnn_normal_pred} | CNN Prediction: {cnn_normal_pred}',
    )

    ax_normal.axis('off')

    ax_shift = axes[i, 1]
    ax_shift.imshow(img_shift.squeeze().numpy(), cmap='plasma')
    ax_shift.set_title(
        f'Shifted Right by 5 (True Label: {label}) \n'
        f'FNN Prediction: {fnn_shift_pred} | CNN Prediction: {cnn_shift_pred}',
        fontsize = 10
    )

    ax_shift.axis('off')

  plt.suptitle('Visual Comparison of Invariance Predictors', fontsize = 14)
  plt.tight_layout()
  plt.show()

visual_differnce(fnn_model, cnn_model, test_dataset, test_dataset_shift, num_img=10)

def metric_comparison(fnn_normal, fnn_shift, cnn_normal, cnn_shift):
  labels = ['Standard Test Set', 'Shifted Test Set']
  fnn_scores = [fnn_normal, fnn_shift]
  cnn_scores = [cnn_normal, cnn_shift]

  x = np.arange(len(labels))
  width = 0.35

  fig, ax = plt.subplots(1, 1, figsize=(8,6))
  rects1 = ax.bar(x - width/2, fnn_scores, width, label='FNN', color='#E24A33')
  rects2 = ax.bar(x + width/2, cnn_scores, width, label='CNN', color='#348ABD')

  ax.set_ylabel('Accuracy')
  ax.set_title('Network Robustness Comparison: Spatial Translation Degradation', fontsize=12)
  ax.set_xticks(x)
  ax.set_xticklabels(labels)
  ax.legend()
  ax.set_ylim(0, 110)

  def autolabel(rects):
        for rect in rects:
            height = rect.get_height()
            ax.annotate(f'{height:.1f}%',
                        xy=(rect.get_x() + rect.get_width() / 2, height),
                        xytext=(0, 3),  # 3 points vertical offset
                        textcoords="offset points",
                        ha='center', va='bottom', fontweight='bold')

  autolabel(rects1)
  autolabel(rects2)

  plt.grid(axis='y', linestyle='--', alpha=0.5)
  plt.tight_layout()
  plt.show()

metric_comparison(fnn_normal_acc, fnn_shift_acc, cnn_normal_acc, cnn_shift_acc)

import os

def save_models(fnn, cnn, directory='./saved_models'):
    if not os.path.exists(directory):
        os.makedirs(directory)
        print(f"\nCreated directory '{directory}' for saving models.")

    fnn_path = os.path.join(directory, 'fnn_mnist.pth')
    cnn_path = os.path.join(directory, 'cnn_mnist.pth')

    torch.save(fnn.state_dict(), fnn_path)
    torch.save(cnn.state_dict(), cnn_path)

    print(f"SUCCESS: Model weights successfully saved to disk.")
    print(f" - FNN weights: {fnn_path}")
    print(f" - CNN weights:  {cnn_path}")


save_models(fnn_model, cnn_model)

